name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:      # Allows manual run from GitHub UI

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "https://dev.to/feed/adityapidurkar"
          comment_tag_name: "BLOG-POST-LIST"  # Matches <!-- BLOG-POST-LIST:START -->
